services:
  postgres:
    image: postgres:latest
    container_name: vax-postgres
    restart: always
    environment:
      POSTGRES_DB: vax
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vax-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vax-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - vax-network

  redis:
    image: redis:latest
    container_name: vax-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - vax-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  vax-network:
    driver: bridge
